export type Product = {
  id: string;
  slug: string;
  name: string;
  shop: string;
  price: number;
  originalPrice: number;
  images: string[];
  rating: number;
  reviews: number;
  sold: number;
  category: string;
  flashSale?: boolean;
  freeship?: boolean;
  tags?: string[];
  description: string;
  origin: string;
  material: string;
  decorType: string;
  hashtags?: string[];
  menh?: string[];
  mua?: string[];
};

export const GLOBAL_HASHTAGS = [
  "#CayCanh",
  "#CayTheoMenh",
  "#CayTheoMua",
  "#CayQuangHopNguoc",
  "#CayTrongNha",
  "#CayTinhYeu",
  "#QuaTangYNghia",
  "#CayPhongThuy",
  "#LocKhongKhi",
  "#DecorNhaCua",
  "#CayVanPhong",
  "#CayDeBan",
  "#CayHopMenh",
  "#CayMayMan",
  "#CayTaiLoc",
  "#QuaTangKhaiTruong",
  "#QuaTangSinhNhat",
  "#Bonsai",
  "#SenDa",
  "#XuongRong",
  "#LanHoDiep",
  "#CayAnQuaMini",
  "#CayChiuBong",
  "#CayUaSang",
  "#CayUaBong",
  "#CayDoiVa",
  "#CayValentine",
  "#CayNgayTet",
  "#CayMuaHe",
  "#CayMuaDong",
  "#GoldenLifeGarden",
  "#PlantShopVN",
];

export type Category = {
  slug: string;
  name: string;
  icon: string;
};

export const categories: Category[] = [
  { slug: "de-ban", name: "Cây để bàn", icon: "🌵" },
  { slug: "phong-thuy", name: "Phong thủy", icon: "🪴" },
  { slug: "trong-nha", name: "Trong nhà", icon: "🌿" },
  { slug: "ngoai-troi", name: "Ngoài trời", icon: "🌳" },
  { slug: "bonsai", name: "Bonsai", icon: "🎋" },
  { slug: "hoa", name: "Hoa cảnh", icon: "🌸" },
  { slug: "chau-cay", name: "Chậu & phụ kiện", icon: "🏺" },
  { slug: "hat-giong", name: "Hạt giống", icon: "🌱" },
];

const IMG = {
  monstera: "https://images.unsplash.com/photo-1614594975525-e45190c55d0b?w=800&q=80",
  monstera2: "https://images.unsplash.com/photo-1632207691143-643e2a9a9361?w=800&q=80",
  senda: "https://images.unsplash.com/photo-1459411552884-841db9b3cc2a?w=800&q=80",
  senda2: "https://images.unsplash.com/photo-1446071103084-c257b5f70672?w=800&q=80",
  xuongrong: "https://images.unsplash.com/photo-1509423350716-97f9360b4e09?w=800&q=80",
  xuongrong2: "https://images.unsplash.com/photo-1459156212016-c812468e2115?w=800&q=80",
  luoiho: "https://images.unsplash.com/photo-1599598425947-5ec6c8a51a07?w=800&q=80",
  luoiho2: "https://images.unsplash.com/photo-1632321285808-55f7c5a42e7d?w=800&q=80",
  kimtien: "https://images.unsplash.com/photo-1632321285820-85c7f2a5f5c8?w=800&q=80",
  phattai: "https://images.unsplash.com/photo-1591958911259-bee2173bdccc?w=800&q=80",
  lany: "https://images.unsplash.com/photo-1616500498638-d7ace4a0e4e4?w=800&q=80",
  trauba: "https://images.unsplash.com/photo-1614594857394-1c4a78e80e66?w=800&q=80",
  trauba2: "https://images.unsplash.com/photo-1602923668104-8f9e03e77e62?w=800&q=80",
  bonsai: "https://images.unsplash.com/photo-1611387661224-7cde9b9cdc64?w=800&q=80",
  bonsai2: "https://images.unsplash.com/photo-1599696848652-f0ff23bc911f?w=800&q=80",
  tunglahan: "https://images.unsplash.com/photo-1606041008023-472dfb5e530f?w=800&q=80",
  hoahong: "https://images.unsplash.com/photo-1496062031456-07b8f162a322?w=800&q=80",
  lanhodi: "https://images.unsplash.com/photo-1567748157439-651aca2ff064?w=800&q=80",
  chau: "https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=800&q=80",
  chau2: "https://images.unsplash.com/photo-1582582494705-f8ce0b0c24f0?w=800&q=80",
  datttrong: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&q=80",
  phanbon: "https://images.unsplash.com/photo-1530836369250-ef72a3f5cda8?w=800&q=80",
  binhtuoi: "https://images.unsplash.com/photo-1558603668-6570496b66f8?w=800&q=80",
  ot: "https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=800&q=80",
  chanh: "https://images.unsplash.com/photo-1582979512210-99b6a53386f9?w=800&q=80",
  lavender: "https://images.unsplash.com/photo-1501862700950-18382cd41497?w=800&q=80",
  huongduong: "https://images.unsplash.com/photo-1470509037663-253afd7f0f51?w=800&q=80",
  caycanh: "https://images.unsplash.com/photo-1459664018906-085c36f472af?w=800&q=80",
  caycanh2: "https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=800&q=80",
  hatgiong: "https://images.unsplash.com/photo-1530836369250-ef72a3f5cda8?w=800&q=80",
  camthach: "https://images.unsplash.com/photo-1587334274328-64186a80aeee?w=800&q=80",
  camthach2: "https://images.unsplash.com/photo-1604762524889-3e2fcc145683?w=800&q=80",
  camthach3: "https://images.unsplash.com/photo-1637967565141-a41e5d48a8d4?w=800&q=80",
  phulau: "https://images.unsplash.com/photo-1587334207407-0b4df17a5ea7?w=800&q=80",
  phulau2: "https://images.unsplash.com/photo-1615213612138-4d1195b1c0e9?w=800&q=80",
  haidang: "https://images.unsplash.com/photo-1600411833114-5c2c2dc4b7e0?w=800&q=80",
  zzplant: "https://images.unsplash.com/photo-1632321285820-85c7f2a5f5c8?w=800&q=80",
  chuoicanh: "https://images.unsplash.com/photo-1545165311-766d3c6a5890?w=800&q=80",
  lolan: "https://images.unsplash.com/photo-1593482892290-f54c7f1c3e16?w=800&q=80",
  caynguyetque: "https://images.unsplash.com/photo-1520412099551-62b6bafeb5bb?w=800&q=80",
  caymayman: "https://images.unsplash.com/photo-1617358014811-52f3ea26c12b?w=800&q=80",
  caytinh: "https://images.unsplash.com/photo-1617516202907-ff28ed9b22e1?w=800&q=80",
};

export const products: Product[] = [
  {
    id: "p1",
    slug: "trau-ba-monstera-size-50cm",
    name: "[Size 50cm] Trầu Bà Thanh Xuân Lá Xẻ chậu nhựa cứng trắng - lọc không khí - decor phòng",
    shop: "Golden Life Garden",
    price: 351052,
    originalPrice: 435000,
    images: [IMG.monstera, IMG.monstera2, IMG.trauba, IMG.trauba2],
    rating: 4.2,
    reviews: 35,
    sold: 329,
    category: "trong-nha",
    flashSale: true,
    freeship: true,
    tags: ["Trang trí phòng", "Cây cao 50cm", "Lỗi 1 đổi 1", "Tặng phụ kiện"],
    description:
      "* Tên Sản Phẩm: Trầu Bà Thanh Xuân Lá Xẻ chậu nhựa cứng trắng\n* Kích Cỡ: Size Lớn 0.5m\n* Chức Năng: Lọc không khí, decor phòng, nhà ở, văn phòng, công ty\n\nTrầu Bà Thanh Xuân (Monstera) Lá Xẻ là dòng cây quang hợp ngược nổi tiếng - ban đêm nhả oxy, hút CO2, rất tốt khi đặt trong phòng ngủ. Cây ưa bóng, dễ chăm, lọc formaldehyde và benzen trong không khí. Hợp mệnh Mộc, Hoả. Biểu tượng cho tình bạn thuỷ chung và tuổi trẻ vĩnh cửu.\n\n✅ Cam kết:\n- Bao sống 7 ngày đầu, lỗi 1 đổi 1\n- Tặng kèm gói phân bón + hướng dẫn chăm\n- Freeship đơn từ 250K\n- Giao nhanh nội thành 2-4h",
    origin: "Việt Nam",
    material: "Nhựa",
    decorType: "Cây cỏ",
    menh: ["Mộc", "Hoả"],
    mua: ["Xuân", "Hạ", "Thu", "Đông"],
    hashtags: [
      "#TrauBaMonstera",
      "#CayQuangHopNguoc",
      "#CayLocKhongKhi",
      "#CayTrongNha",
      "#CayDecorPhong",
      "#GoldenLifeGarden",
      "#CayUaBong",
      "#CayHopMenhMoc",
      "#QuaTangKhaiTruong",
      "#CayPhongNgu",
      "#CayVanPhong",
      "#MonsteraDeliciosa",
    ],
  },
  {
    id: "p2",
    slug: "sen-da-mini-5-cay",
    name: "Combo 5 Cây Sen Đá Mini Để Bàn Làm Việc - Dễ Chăm Sóc",
    shop: "Succulent House",
    price: 89000,
    originalPrice: 150000,
    images: [IMG.senda, IMG.senda2],
    rating: 4.9,
    reviews: 1243,
    sold: 5892,
    category: "de-ban",
    flashSale: true,
    freeship: true,
    tags: ["Combo 5 cây", "Dễ chăm", "Bao sống"],
    description: "Combo 5 cây sen đá mini đủ loại, kèm chậu sứ nhỏ xinh. Dễ chăm, hợp mệnh.",
    origin: "Đà Lạt",
    material: "Cây tươi",
    decorType: "Sen đá",
  },
  {
    id: "p3",
    slug: "xuong-rong-mini-combo",
    name: "Set 4 Cây Xương Rồng Mini Tặng Kèm Chậu Đá - Decor Bàn",
    shop: "Cactus Store",
    price: 65000,
    originalPrice: 120000,
    images: [IMG.xuongrong, IMG.xuongrong2],
    rating: 4.8,
    reviews: 892,
    sold: 3421,
    category: "de-ban",
    flashSale: true,
    freeship: true,
    tags: ["Set 4 cây", "Tặng chậu"],
    description: "Set 4 cây xương rồng mini tặng kèm chậu đá tự nhiên. Cây khỏe, gai mềm.",
    origin: "Ninh Thuận",
    material: "Cây tươi",
    decorType: "Xương rồng",
  },
  {
    id: "p4",
    slug: "luoi-ho-van-phong",
    name: "Cây Lưỡi Hổ Viền Vàng - Chậu Sứ Trắng - Lọc Khí Cao Cấp",
    shop: "Green Office",
    price: 185000,
    originalPrice: 280000,
    images: [IMG.luoiho, IMG.luoiho2],
    rating: 4.7,
    reviews: 567,
    sold: 2103,
    category: "phong-thuy",
    freeship: true,
    tags: ["Lọc không khí", "Phong thủy"],
    description: "Cây lưỡi hổ viền vàng cao 40-50cm, chậu sứ trắng sang trọng. Hợp mệnh Thổ, Kim.",
    origin: "Việt Nam",
    material: "Cây tươi + sứ",
    decorType: "Cây để bàn",
  },
  {
    id: "p5",
    slug: "kim-tien-phong-thuy",
    name: "Cây Kim Tiền Phong Thủy - Hút Tài Lộc - Chậu Sứ Cao Cấp",
    shop: "Phong Thủy Việt",
    price: 320000,
    originalPrice: 499000,
    images: [IMG.kimtien, IMG.caycanh],
    rating: 4.9,
    reviews: 2341,
    sold: 8921,
    category: "phong-thuy",
    flashSale: true,
    freeship: true,
    tags: ["Hút tài lộc", "Quà tặng khai trương"],
    description: "Cây kim tiền cao 60-70cm, lá xanh bóng, chậu sứ cao cấp. Quà khai trương ý nghĩa.",
    origin: "Việt Nam",
    material: "Cây tươi + sứ",
    decorType: "Phong thủy",
  },
  {
    id: "p6",
    slug: "phat-tai-nui",
    name: "Cây Phát Tài Núi - Thân Gỗ Cao 80cm - Hợp Mọi Mệnh",
    shop: "Phong Thủy Việt",
    price: 450000,
    originalPrice: 650000,
    images: [IMG.phattai],
    rating: 4.8,
    reviews: 423,
    sold: 1567,
    category: "phong-thuy",
    freeship: true,
    tags: ["Cao 80cm", "Phong thủy"],
    description: "Cây phát tài núi thân gỗ cao 80cm, lá xanh mướt, mang lại may mắn.",
    origin: "Việt Nam",
    material: "Cây tươi",
    decorType: "Phong thủy",
  },
  {
    id: "p7",
    slug: "lan-y-thanh-loc",
    name: "Cây Lan Ý - Hoa Trắng Tinh Khôi - Lọc Không Khí Số 1",
    shop: "Green Office",
    price: 155000,
    originalPrice: 220000,
    images: [IMG.lany],
    rating: 4.6,
    reviews: 678,
    sold: 2845,
    category: "trong-nha",
    freeship: true,
    tags: ["Lọc không khí", "Hoa trắng"],
    description: "Cây lan ý ra hoa trắng quanh năm, NASA xếp hạng cây lọc không khí tốt nhất.",
    origin: "Việt Nam",
    material: "Cây tươi",
    decorType: "Cây trong nhà",
  },
  {
    id: "p8",
    slug: "bonsai-mini-de-ban",
    name: "Bonsai Mini Tùng La Hán - Dáng Thác Đổ - Để Bàn",
    shop: "Bonsai Art",
    price: 780000,
    originalPrice: 1200000,
    images: [IMG.bonsai, IMG.bonsai2],
    rating: 4.9,
    reviews: 234,
    sold: 567,
    category: "bonsai",
    tags: ["Dáng thác đổ", "Thủ công"],
    description: "Bonsai tùng la hán dáng thác đổ, thế đẹp, được uốn tỉa thủ công bởi nghệ nhân.",
    origin: "Nam Định",
    material: "Cây tươi + chậu gốm",
    decorType: "Bonsai",
  },
  {
    id: "p9",
    slug: "tung-la-han-thang",
    name: "Cây Tùng La Hán Dáng Thẳng Cao 1.2m - Sân Vườn",
    shop: "Bonsai Art",
    price: 1250000,
    originalPrice: 1800000,
    images: [IMG.tunglahan],
    rating: 4.8,
    reviews: 89,
    sold: 234,
    category: "ngoai-troi",
    tags: ["Cao 1.2m", "Sân vườn"],
    description: "Tùng la hán dáng thẳng cao 1.2m, phù hợp sân vườn, biệt thự.",
    origin: "Nam Định",
    material: "Cây tươi",
    decorType: "Cây ngoài trời",
  },
  {
    id: "p10",
    slug: "hoa-hong-leo",
    name: "Cây Hoa Hồng Leo Pháp - Nhiều Màu - Hoa Nở Quanh Năm",
    shop: "Rose Garden",
    price: 125000,
    originalPrice: 200000,
    images: [IMG.hoahong],
    rating: 4.7,
    reviews: 1567,
    sold: 6234,
    category: "hoa",
    flashSale: true,
    freeship: true,
    tags: ["Hoa nở quanh năm", "Nhiều màu"],
    description: "Hoa hồng leo Pháp, sai hoa, nhiều màu (đỏ/hồng/vàng). Phù hợp ban công, sân vườn.",
    origin: "Đà Lạt",
    material: "Cây tươi",
    decorType: "Hoa cảnh",
  },
  {
    id: "p11",
    slug: "lan-ho-diep-5-canh",
    name: "Chậu Lan Hồ Điệp 5 Cành - Hoa Tươi Lâu - Quà Tặng Cao Cấp",
    shop: "Luxury Orchid",
    price: 890000,
    originalPrice: 1500000,
    images: [IMG.lanhodi],
    rating: 4.9,
    reviews: 456,
    sold: 1234,
    category: "hoa",
    tags: ["5 cành", "Quà tặng"],
    description: "Chậu lan hồ điệp 5 cành, hoa tươi 2-3 tháng, phù hợp làm quà tặng khai trương.",
    origin: "Đà Lạt",
    material: "Hoa tươi",
    decorType: "Hoa cảnh",
  },
  {
    id: "p12",
    slug: "chau-su-tron-trang",
    name: "Chậu Sứ Tròn Trắng Cao Cấp Size M - Trồng Cây Cảnh",
    shop: "Ceramic Craft",
    price: 85000,
    originalPrice: 150000,
    images: [IMG.chau, IMG.chau2],
    rating: 4.8,
    reviews: 2134,
    sold: 8923,
    category: "chau-cay",
    flashSale: true,
    freeship: true,
    tags: ["Sứ cao cấp", "Size M"],
    description: "Chậu sứ tròn trắng size M (20cm), chất sứ cao cấp, lỗ thoát nước chuẩn.",
    origin: "Bát Tràng",
    material: "Sứ",
    decorType: "Chậu cây",
  },
  {
    id: "p13",
    slug: "dat-trong-sach",
    name: "Đất Trồng Sạch Dinh Dưỡng 5kg - Cho Mọi Loại Cây Cảnh",
    shop: "Plant Care VN",
    price: 45000,
    originalPrice: 80000,
    images: [IMG.datttrong],
    rating: 4.8,
    reviews: 3456,
    sold: 12893,
    category: "chau-cay",
    flashSale: true,
    freeship: true,
    tags: ["5kg", "Dinh dưỡng"],
    description: "Đất trồng sạch trộn sẵn dinh dưỡng, túi 5kg, phù hợp mọi loại cây.",
    origin: "Việt Nam",
    material: "Đất hữu cơ",
    decorType: "Phụ kiện",
  },
  {
    id: "p14",
    slug: "phan-bon-huu-co",
    name: "Phân Bón Hữu Cơ Trùn Quế 1kg - An Toàn - Không Mùi",
    shop: "Plant Care VN",
    price: 35000,
    originalPrice: 60000,
    images: [IMG.phanbon],
    rating: 4.9,
    reviews: 2341,
    sold: 9821,
    category: "chau-cay",
    freeship: true,
    tags: ["Hữu cơ", "Không mùi"],
    description: "Phân bón trùn quế hữu cơ 1kg, an toàn cho trẻ em và thú cưng.",
    origin: "Việt Nam",
    material: "Hữu cơ",
    decorType: "Phụ kiện",
  },
  {
    id: "p15",
    slug: "binh-tuoi-cay-mini",
    name: "Bình Tưới Cây Mini 500ml - Thiết Kế Cute - Nhiều Màu",
    shop: "Garden Tool",
    price: 59000,
    originalPrice: 99000,
    images: [IMG.binhtuoi],
    rating: 4.7,
    reviews: 1234,
    sold: 5623,
    category: "chau-cay",
    freeship: true,
    tags: ["500ml", "Nhiều màu"],
    description: "Bình tưới cây mini 500ml thiết kế xinh xắn, có vòi dài tưới chính xác.",
    origin: "Việt Nam",
    material: "Nhựa",
    decorType: "Dụng cụ",
  },
  {
    id: "p16",
    slug: "ot-kieng-mini",
    name: "Cây Ớt Kiểng 7 Màu Mini - Ra Quả Quanh Năm - Decor",
    shop: "Mini Garden",
    price: 55000,
    originalPrice: 89000,
    images: [IMG.ot],
    rating: 4.8,
    reviews: 892,
    sold: 3456,
    category: "de-ban",
    freeship: true,
    tags: ["7 màu", "Ra quả quanh năm"],
    description: "Cây ớt kiểng 7 màu mini, ra quả quanh năm, vừa đẹp vừa cay.",
    origin: "Đà Lạt",
    material: "Cây tươi",
    decorType: "Cây ăn quả mini",
  },
  {
    id: "p17",
    slug: "chanh-ngon-tay",
    name: "Cây Chanh Ngón Tay Finger Lime - Cây Ghép Cao 60cm",
    shop: "Exotic Fruit",
    price: 650000,
    originalPrice: 950000,
    images: [IMG.chanh],
    rating: 4.6,
    reviews: 156,
    sold: 423,
    category: "ngoai-troi",
    tags: ["Cây ghép", "Cao 60cm"],
    description: "Cây chanh ngón tay Úc ghép, cao 60cm, đã ra quả. Quả hiếm, đắt đỏ.",
    origin: "Việt Nam",
    material: "Cây tươi",
    decorType: "Cây ăn quả",
  },
  {
    id: "p18",
    slug: "lavender-oải-hương",
    name: "Cây Lavender Oải Hương Pháp - Hoa Tím Thơm Dịu",
    shop: "Rose Garden",
    price: 135000,
    originalPrice: 200000,
    images: [IMG.lavender],
    rating: 4.5,
    reviews: 789,
    sold: 2341,
    category: "hoa",
    freeship: true,
    tags: ["Hoa tím", "Thơm dịu"],
    description: "Cây lavender oải hương Pháp, hoa tím thơm dịu, đuổi muỗi tự nhiên.",
    origin: "Đà Lạt",
    material: "Cây tươi",
    decorType: "Hoa cảnh",
  },
  {
    id: "p19",
    slug: "huong-duong-mini",
    name: "Cây Hướng Dương Mini Lùn - Nở Hoa Trong 60 Ngày",
    shop: "Mini Garden",
    price: 45000,
    originalPrice: 75000,
    images: [IMG.huongduong],
    rating: 4.7,
    reviews: 567,
    sold: 1892,
    category: "hoa",
    flashSale: true,
    freeship: true,
    tags: ["Lùn", "Nở 60 ngày"],
    description: "Hướng dương mini lùn, cao 30-40cm, nở hoa sau 60 ngày gieo. Hạt giống kèm đất.",
    origin: "Việt Nam",
    material: "Cây tươi",
    decorType: "Hoa cảnh",
  },
  {
    id: "p20",
    slug: "hat-giong-rau-sach",
    name: "Combo 10 Gói Hạt Giống Rau Sạch - Trồng Ban Công",
    shop: "Seed VN",
    price: 39000,
    originalPrice: 75000,
    images: [IMG.hatgiong],
    rating: 4.8,
    reviews: 4567,
    sold: 18923,
    category: "hat-giong",
    flashSale: true,
    freeship: true,
    tags: ["10 gói", "Ban công"],
    description: "Combo 10 gói hạt giống rau sạch đủ loại: rau muống, cải, xà lách, hành, tỏi...",
    origin: "Việt Nam",
    material: "Hạt giống",
    decorType: "Hạt giống",
  },
  {
    id: "p21",
    slug: "trau-ba-xanh-leo-cot",
    name: "Cây Trầu Bà Xanh Leo Cột - Cao 1m - Trang Trí Văn Phòng",
    shop: "Green Office",
    price: 295000,
    originalPrice: 450000,
    images: [IMG.trauba, IMG.trauba2],
    rating: 4.8,
    reviews: 567,
    sold: 2341,
    category: "trong-nha",
    freeship: true,
    tags: ["Cao 1m", "Leo cột"],
    description: "Cây trầu bà xanh leo cột cao 1m, chậu sứ trắng, tạo không gian xanh cho văn phòng.",
    origin: "Việt Nam",
    material: "Cây tươi",
    decorType: "Cây trong nhà",
  },
  {
    id: "p22",
    slug: "chau-gom-bat-trang",
    name: "Chậu Gốm Bát Tràng Họa Tiết Sen - Size L - Cao Cấp",
    shop: "Ceramic Craft",
    price: 145000,
    originalPrice: 240000,
    images: [IMG.chau2],
    rating: 4.9,
    reviews: 789,
    sold: 2134,
    category: "chau-cay",
    freeship: true,
    tags: ["Bát Tràng", "Size L"],
    description: "Chậu gốm Bát Tràng vẽ tay họa tiết sen, size L (30cm), sang trọng.",
    origin: "Bát Tràng",
    material: "Gốm",
    decorType: "Chậu cây",
  },
  {
    id: "p23",
    slug: "sen-da-nhat-ban",
    name: "Cây Sen Đá Nhật Tai Thỏ - Chậu Sứ Trắng - Dễ Chăm",
    shop: "Succulent House",
    price: 45000,
    originalPrice: 80000,
    images: [IMG.senda],
    rating: 4.7,
    reviews: 2134,
    sold: 8921,
    category: "de-ban",
    flashSale: true,
    freeship: true,
    tags: ["Nhật Bản", "Tai thỏ"],
    description: "Sen đá Nhật tai thỏ, dáng cute, chậu sứ trắng kèm đá trang trí.",
    origin: "Nhật Bản",
    material: "Cây tươi",
    decorType: "Sen đá",
  },
  {
    id: "p24",
    slug: "xuong-rong-than-cao",
    name: "Xương Rồng Thân Cao 30cm - Decor Bắc Âu - Chậu Xi Măng",
    shop: "Cactus Store",
    price: 180000,
    originalPrice: 290000,
    images: [IMG.xuongrong2],
    rating: 4.7,
    reviews: 345,
    sold: 1234,
    category: "de-ban",
    freeship: true,
    tags: ["30cm", "Bắc Âu"],
    description: "Xương rồng thân cao 30cm, chậu xi măng phong cách Bắc Âu tối giản.",
    origin: "Ninh Thuận",
    material: "Cây tươi",
    decorType: "Xương rồng",
    menh: ["Kim"],
    mua: ["Hạ"],
    hashtags: ["#XuongRong", "#CayDeBan", "#DecorBacAu", "#CayHopMenhKim"],
  },
  // ========== Golden Life Garden ==========
  {
    id: "glg1",
    slug: "cay-cam-thach-golden-life-garden",
    name: "Cây Cẩm Thạch Lá Bạc - Chậu Sứ Cao Cấp - Decor Nhà Độc Đáo",
    shop: "Golden Life Garden",
    price: 285000,
    originalPrice: 420000,
    images: [IMG.camthach, IMG.camthach2, IMG.camthach3, IMG.trauba],
    rating: 4.8,
    reviews: 1243,
    sold: 4821,
    category: "trong-nha",
    flashSale: true,
    freeship: true,
    tags: ["Cây độc đáo", "Lá bạc", "Tặng phụ kiện", "Lỗi 1 đổi 1"],
    description:
      "* Tên Sản Phẩm: Cây Cẩm Thạch (Scindapsus Pictus Argyraeus) - Lá đốm bạc độc đáo\n* Kích Cỡ: Cao 30-40cm, chậu sứ trắng\n* Chức Năng: Lọc không khí, trang trí nhà cửa, văn phòng\n\nCẩm Thạch là dòng cây hiếm có lá xanh đậm điểm những đốm bạc lấp lánh - được ví như những viên đá quý trên cành. Cây thuộc họ Ráy, dễ chăm, ưa bóng, phù hợp đặt bàn làm việc, kệ sách, phòng khách.\n\n✅ Đặc điểm:\n- Lá dày, đốm bạc tự nhiên, không phai màu\n- Cây khoẻ, đã thuần dưỡng 3-6 tháng\n- Lọc formaldehyde và xylene trong không khí\n- Hợp mệnh Mộc, Thuỷ\n- Ý nghĩa: May mắn, tài lộc, vững bền\n\n🎁 Tặng kèm:\n- Gói phân bón chuyên dụng\n- Hướng dẫn chăm sóc chi tiết\n- Thiệp ghi lời chúc (nếu là quà tặng)",
    origin: "Việt Nam",
    material: "Cây tươi + chậu sứ",
    decorType: "Cây trang trí độc đáo",
    menh: ["Mộc", "Thuỷ"],
    mua: ["Xuân", "Hạ", "Thu", "Đông"],
    hashtags: [
      "#CayCamThach",
      "#ScindapsusPictus",
      "#CayLaBac",
      "#CayHiem",
      "#GoldenLifeGarden",
      "#CayTrongNha",
      "#CayDecor",
      "#CayVanPhong",
      "#CayQuaTang",
      "#CayHopMenhMoc",
      "#CayHopMenhThuy",
      "#LocKhongKhi",
      "#CayDecorDocDao",
      "#PlantLover",
    ],
  },
  {
    id: "glg2",
    slug: "cay-phu-lau-golden-life",
    name: "Cây Phú Lâu - Phong Thuỷ Hút Tài Lộc - Chậu Sứ Trắng Size Lớn",
    shop: "Golden Life Garden",
    price: 395000,
    originalPrice: 580000,
    images: [IMG.phulau, IMG.phulau2, IMG.kimtien],
    rating: 4.9,
    reviews: 892,
    sold: 3124,
    category: "phong-thuy",
    flashSale: true,
    freeship: true,
    tags: ["Hút tài lộc", "Cây phong thuỷ", "Cao 50cm"],
    description:
      "Cây Phú Lâu (Pachira Aquatica) thân bện, lá xanh mướt 5 cánh - biểu tượng may mắn của ngũ hành. Trong phong thuỷ, cây hút tài lộc, giữ của, đem lại thịnh vượng cho gia chủ.\n\n✅ Ý nghĩa:\n- 5 lá tượng trưng: Kim - Mộc - Thuỷ - Hoả - Thổ\n- Thân bện = đoàn kết, gắn bó gia đình\n- Quà khai trương, tân gia, sinh nhật sếp\n\n🎁 Quà đi kèm:\n- Bao lì xì đỏ may mắn\n- Đá phong thuỷ trang trí\n- Thiệp ghi lời chúc",
    origin: "Việt Nam",
    material: "Cây tươi + chậu sứ",
    decorType: "Cây phong thuỷ",
    menh: ["Mộc", "Hoả", "Thổ"],
    mua: ["Xuân", "Hạ", "Thu", "Đông"],
    hashtags: [
      "#CayPhuLau",
      "#PachiraAquatica",
      "#CayPhongThuy",
      "#CayHutTaiLoc",
      "#GoldenLifeGarden",
      "#QuaTangKhaiTruong",
      "#CayMayMan",
      "#CayHopMenh",
      "#CayNguHanh",
      "#CayThanBen",
      "#QuaTanGia",
    ],
  },
  {
    id: "glg3",
    slug: "cay-hai-dang-rung-golden-life",
    name: "Cây Hải Đăng Rủ - Leo Cột Cao 80cm - Decor Phòng Khách",
    shop: "Golden Life Garden",
    price: 325000,
    originalPrice: 490000,
    images: [IMG.haidang, IMG.trauba, IMG.trauba2],
    rating: 4.7,
    reviews: 567,
    sold: 1892,
    category: "trong-nha",
    freeship: true,
    tags: ["Leo cột", "Cao 80cm", "Lá rủ đẹp"],
    description:
      "Cây Hải Đăng (Epipremnum Aureum) lá vàng xanh cẩm thạch, dáng rủ mềm mại. Leo cột cao 80cm, phù hợp treo ban công, decor phòng khách, kệ cao. Lọc không khí top NASA.\n\n✅ Ưu điểm:\n- Lá cẩm thạch vàng xanh bắt mắt\n- Dễ chăm, chịu bóng tốt\n- Lọc CO, formaldehyde, benzen\n- Mọc nhanh, dáng rủ đẹp mắt",
    origin: "Việt Nam",
    material: "Cây tươi + chậu sứ",
    decorType: "Cây rủ trang trí",
    menh: ["Mộc"],
    mua: ["Xuân", "Hạ", "Thu"],
    hashtags: [
      "#CayHaiDang",
      "#EpipremnumAureum",
      "#CayRu",
      "#CayLeoCot",
      "#GoldenLifeGarden",
      "#CayDecorPhongKhach",
      "#CayBanCong",
      "#CayLocKhongKhiTopNASA",
    ],
  },
  {
    id: "glg4",
    slug: "cay-zz-golden-life",
    name: "Cây Kim Phát Tài ZZ - Chịu Bóng Tốt - Phong Thuỷ Tài Lộc",
    shop: "Golden Life Garden",
    price: 255000,
    originalPrice: 380000,
    images: [IMG.zzplant, IMG.kimtien, IMG.phattai],
    rating: 4.9,
    reviews: 1567,
    sold: 5234,
    category: "phong-thuy",
    flashSale: true,
    freeship: true,
    tags: ["Chịu bóng", "Ít nước", "Phong thuỷ"],
    description:
      "Cây ZZ (Zamioculcas Zamiifolia) - Kim Phát Tài lá xanh bóng đẹp, thân mập, siêu dễ chăm. Cây chịu bóng và khô hạn cực tốt, 2 tuần mới cần tưới 1 lần. Hợp văn phòng đóng kín, phòng ngủ.\n\n✅ Tại sao nên mua:\n- Siêu dễ chăm, hợp người bận rộn\n- Chịu được điều hoà, ánh sáng yếu\n- Phong thuỷ: Hút tài, giữ của\n- Lá bóng đẹp quanh năm",
    origin: "Việt Nam",
    material: "Cây tươi + chậu sứ",
    decorType: "Cây phong thuỷ",
    menh: ["Mộc", "Thổ"],
    mua: ["Xuân", "Hạ", "Thu", "Đông"],
    hashtags: [
      "#CayZZ",
      "#KimPhatTai",
      "#ZamioculcasZamiifolia",
      "#CayChiuBong",
      "#GoldenLifeGarden",
      "#CayDeChCham",
      "#CayVanPhong",
      "#CayPhongNgu",
      "#CayItNuoc",
      "#PhongThuyTaiLoc",
    ],
  },
  {
    id: "glg5",
    slug: "cay-chuoi-canh-rung-golden-life",
    name: "Cây Chuối Cảnh Rừng Nhiệt Đới - Cao 1.2m - Decor Sang Trọng",
    shop: "Golden Life Garden",
    price: 685000,
    originalPrice: 980000,
    images: [IMG.chuoicanh, IMG.haidang, IMG.trauba2],
    rating: 4.8,
    reviews: 234,
    sold: 678,
    category: "trong-nha",
    freeship: true,
    tags: ["Cao 1.2m", "Nhiệt đới", "Sang trọng"],
    description:
      "Cây Chuối Cảnh (Musa) - cây nhiệt đới cao 1.2m, lá to xanh mướt tạo cảm giác như đang ở resort. Phù hợp phòng khách, quán cafe, studio chụp ảnh.\n\n✅ Đặc điểm:\n- Lá to 40-60cm, xanh bóng\n- Chiều cao tổng thể 1.2m\n- Phù hợp không gian lớn, trần cao\n- Cây thuần dưỡng trong nhà, không bị rụng lá",
    origin: "Việt Nam",
    material: "Cây tươi + chậu xi măng",
    decorType: "Cây nhiệt đới",
    menh: ["Mộc", "Thuỷ"],
    mua: ["Xuân", "Hạ"],
    hashtags: [
      "#CayChuoiCanh",
      "#CayNhietDoi",
      "#GoldenLifeGarden",
      "#DecorSangTrong",
      "#CayCafe",
      "#CayStudio",
      "#CayPhongKhach",
    ],
  },
  {
    id: "glg6",
    slug: "cay-lo-lan-golden-life-tinh-yeu",
    name: "Cây Lô Lan Tình Yêu - Hình Trái Tim - Quà Tặng Valentine",
    shop: "Golden Life Garden",
    price: 165000,
    originalPrice: 250000,
    images: [IMG.caytinh, IMG.lolan, IMG.senda],
    rating: 4.9,
    reviews: 2341,
    sold: 8923,
    category: "de-ban",
    flashSale: true,
    freeship: true,
    tags: ["Hình trái tim", "Quà Valentine", "Cây tình yêu"],
    description:
      "Cây Lô Lan (Hoya Kerrii) - cây tình yêu với lá hình trái tim độc đáo. Món quà Valentine, kỷ niệm yêu, sinh nhật vợ/người yêu ý nghĩa nhất.\n\n💚 Ý nghĩa:\n- Lá hình trái tim = tình yêu vững bền\n- Cây sống lâu 10+ năm = tình yêu mãi mãi\n- Dễ chăm, ít nước\n\n🎁 Tặng kèm:\n- Hộp quà thiết kế Valentine\n- Thiệp ghi lời nhắn theo yêu cầu\n- Chậu sứ mini đáng yêu",
    origin: "Thái Lan",
    material: "Cây tươi + chậu sứ",
    decorType: "Cây tình yêu",
    menh: ["Hoả", "Thổ"],
    mua: ["Xuân", "Hạ", "Thu", "Đông"],
    hashtags: [
      "#CayTinhYeu",
      "#CayLoLan",
      "#HoyaKerrii",
      "#CayHinhTraiTim",
      "#QuaTangValentine",
      "#GoldenLifeGarden",
      "#QuaTangSinhNhat",
      "#QuaTangNguoiYeu",
      "#CayDeBan",
      "#HeartPlant",
    ],
  },
  {
    id: "glg7",
    slug: "cay-nguyet-que-golden-life",
    name: "Cây Nguyệt Quế Thơm - Ra Hoa Quanh Năm - Phong Thuỷ Cát Tường",
    shop: "Golden Life Garden",
    price: 395000,
    originalPrice: 590000,
    images: [IMG.caynguyetque, IMG.hoahong],
    rating: 4.8,
    reviews: 678,
    sold: 2341,
    category: "phong-thuy",
    freeship: true,
    tags: ["Ra hoa quanh năm", "Hương thơm"],
    description:
      "Cây Nguyệt Quế (Murraya Paniculata) - hoa trắng thơm ngát, ra hoa quanh năm. Phong thuỷ: Đem lại may mắn, vượng khí, đuổi tà. Cây quà Tết, khai trương rất ý nghĩa.\n\n✅ Đặc điểm:\n- Hoa trắng nhỏ, thơm nồng như hoa bưởi\n- Ra hoa 4-6 đợt/năm\n- Lá xanh bóng đẹp\n- Cao 50-70cm, chậu sứ",
    origin: "Việt Nam",
    material: "Cây tươi + chậu sứ",
    decorType: "Cây có hoa thơm",
    menh: ["Mộc", "Kim"],
    mua: ["Xuân", "Hạ", "Thu"],
    hashtags: [
      "#CayNguyetQue",
      "#MurrayaPaniculata",
      "#CayCoHoaThom",
      "#GoldenLifeGarden",
      "#CayPhongThuy",
      "#QuaTangTet",
      "#CayCatTuong",
      "#CayDuoiTa",
    ],
  },
  {
    id: "glg8",
    slug: "cay-kim-ngan-golden-life-may-man",
    name: "Cây Kim Ngân Than Bện 3 Thân - May Mắn Tài Lộc - Chậu Sứ Lớn",
    shop: "Golden Life Garden",
    price: 495000,
    originalPrice: 750000,
    images: [IMG.caymayman, IMG.kimtien, IMG.phattai],
    rating: 4.9,
    reviews: 1234,
    sold: 4567,
    category: "phong-thuy",
    flashSale: true,
    freeship: true,
    tags: ["Thân bện 3", "May mắn", "Khai trương"],
    description:
      "Cây Kim Ngân (Pachira Aquatica) thân bện 3 cao 70cm - biểu tượng Tam Tài (Thiên-Địa-Nhân). Quà khai trương, tân gia, tặng sếp hàng đầu. Cây khoẻ, dễ chăm, lá xanh quanh năm.\n\n✅ Phong thuỷ:\n- 3 thân bện = Tam Tài hội tụ\n- Lá 5 cánh = Ngũ Hành đầy đủ\n- Đặt Đông-Nam đón vận may tiền tài\n- Hợp mệnh Mộc, Hoả, Thổ\n\n🎁 Đi kèm:\n- Nơ đỏ khai trương\n- Thiệp chúc mừng",
    origin: "Việt Nam",
    material: "Cây tươi + chậu sứ lớn",
    decorType: "Cây phong thuỷ",
    menh: ["Mộc", "Hoả", "Thổ"],
    mua: ["Xuân", "Hạ", "Thu", "Đông"],
    hashtags: [
      "#CayKimNgan",
      "#PachiraAquatica",
      "#CayPhongThuy",
      "#CayThanBen3",
      "#GoldenLifeGarden",
      "#QuaTangKhaiTruong",
      "#QuaTanGia",
      "#QuaTangSep",
      "#TamTai",
      "#NguHanh",
    ],
  },
  {
    id: "glg9",
    slug: "cay-luoi-ho-vang-golden-life",
    name: "Cây Lưỡi Hổ Vàng Mini - Bộ 3 Chậu Sứ - Lọc Không Khí Phòng Ngủ",
    shop: "Golden Life Garden",
    price: 185000,
    originalPrice: 290000,
    images: [IMG.luoiho, IMG.luoiho2, IMG.senda],
    rating: 4.8,
    reviews: 3456,
    sold: 12893,
    category: "trong-nha",
    flashSale: true,
    freeship: true,
    tags: ["Combo 3", "Quang hợp ngược", "Phòng ngủ"],
    description:
      "Combo 3 chậu Lưỡi Hổ Vàng (Sansevieria Trifasciata) mini - cây quang hợp ngược nổi tiếng, ban đêm nhả oxy cực tốt, đặt đầu giường ngủ ngon hơn.\n\n✅ Tại sao đặt phòng ngủ:\n- Quang hợp CAM - nhả O2 ban đêm\n- Hút CO2, formaldehyde, trichloroethylene\n- Theo NASA: top 10 cây lọc không khí tốt nhất\n- Hợp mệnh Thổ, Kim\n\n🎁 Bộ 3 chậu mini size phù hợp đặt bàn làm việc, đầu giường.",
    origin: "Việt Nam",
    material: "Cây tươi + chậu sứ",
    decorType: "Cây quang hợp ngược",
    menh: ["Thổ", "Kim"],
    mua: ["Xuân", "Hạ", "Thu", "Đông"],
    hashtags: [
      "#CayLuoiHo",
      "#SansevieriaTrifasciata",
      "#CayQuangHopNguoc",
      "#CayPhongNgu",
      "#GoldenLifeGarden",
      "#TopNASA",
      "#CayLocKhongKhi",
      "#CayHopMenhTho",
      "#CayHopMenhKim",
      "#CayDeChCham",
    ],
  },
  {
    id: "glg10",
    slug: "cay-trau-ba-cam-thach-golden-life",
    name: "Cây Trầu Bà Cẩm Thạch - Lá Loang Trắng Hiếm - Size 40cm",
    shop: "Golden Life Garden",
    price: 445000,
    originalPrice: 680000,
    images: [IMG.camthach, IMG.trauba, IMG.camthach2, IMG.camthach3],
    rating: 4.9,
    reviews: 456,
    sold: 1234,
    category: "trong-nha",
    freeship: true,
    tags: ["Cây hiếm", "Lá loang trắng", "40cm"],
    description:
      "Trầu Bà Cẩm Thạch (Epipremnum Aureum 'Marble Queen') - dòng trầu bà đột biến với lá loang trắng sữa độc đáo. Mỗi lá có hoa văn khác nhau, không lá nào giống lá nào.\n\n✅ Đặc điểm:\n- Lá loang trắng tự nhiên do đột biến gene\n- Cây càng lớn vân càng đẹp\n- Ưa bóng, dễ chăm\n- Phong thuỷ: May mắn, tài lộc",
    origin: "Việt Nam",
    material: "Cây tươi + chậu sứ",
    decorType: "Cây cẩm thạch",
    menh: ["Mộc", "Kim"],
    mua: ["Xuân", "Hạ", "Thu", "Đông"],
    hashtags: [
      "#TrauBaCamThach",
      "#MarbleQueen",
      "#CayDotBien",
      "#CayHiem",
      "#GoldenLifeGarden",
      "#CayCamThach",
      "#CayLaLoangTrang",
      "#CayDecorDocDao",
    ],
  },
];

export function getProduct(id: string): Product | undefined {
  return products.find((p) => p.id === id || p.slug === id);
}

export function getProductsByCategory(slug: string): Product[] {
  return products.filter((p) => p.category === slug);
}

export function getFlashSaleProducts(): Product[] {
  return products.filter((p) => p.flashSale);
}

export function shopSlug(name: string): string {
  return name
    .toLowerCase()
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .replace(/đ/g, "d")
    .replace(/[^a-z0-9\s-]/g, "")
    .trim()
    .replace(/\s+/g, "-");
}

export function getShops() {
  const map = new Map<string, { name: string; slug: string; count: number }>();
  for (const p of products) {
    const slug = shopSlug(p.shop);
    const existing = map.get(slug);
    if (existing) existing.count += 1;
    else map.set(slug, { name: p.shop, slug, count: 1 });
  }
  return Array.from(map.values());
}

export function getProductsByShopSlug(slug: string): Product[] {
  return products.filter((p) => shopSlug(p.shop) === slug);
}

export function getShopByName(name: string) {
  const slug = shopSlug(name);
  return getShops().find((s) => s.slug === slug);
}

export function searchProducts(q: string): Product[] {
  const query = q.toLowerCase().replace(/^#/, "").trim();
  if (!query) return products;
  return products.filter(
    (p) =>
      p.name.toLowerCase().includes(query) ||
      p.shop.toLowerCase().includes(query) ||
      p.description.toLowerCase().includes(query) ||
      p.decorType.toLowerCase().includes(query) ||
      p.tags?.some((t) => t.toLowerCase().includes(query)) ||
      p.hashtags?.some((h) => h.toLowerCase().replace(/^#/, "").includes(query)) ||
      p.menh?.some((m) => m.toLowerCase().includes(query)) ||
      p.mua?.some((m) => m.toLowerCase().includes(query))
  );
}
